# .cpanel.yml
---
deployment:
  tasks:
    - 'APPDIR=/home/greagfup/apps/great-owl-stage; VENV=/home/greagfup/virtualenv/apps/great-owl-stage/3.12; $VENV/bin/pip install --upgrade -r $APPDIR/requirements.txt'
    - 'APPDIR=/home/greagfup/apps/great-owl-stage; VENV=/home/greagfup/virtualenv/apps/great-owl-stage/3.12; cd $APPDIR && $VENV/bin/python manage.py migrate --noinput'
    - 'APPDIR=/home/greagfup/apps/great-owl-stage; VENV=/home/greagfup/virtualenv/apps/great-owl-stage/3.12; cd $APPDIR && $VENV/bin/python manage.py collectstatic --noinput'
    - 'APPDIR=/home/greagfup/apps/great-owl-stage; /bin/touch $APPDIR/passenger_wsgi.py'

