# .cpanel.yml
---
deployment:
  tasks:
    - export APPDIR=/home/greagfup/apps/great-owl
    - export VENV=/home/greagfup/virtualenv/great-owl/3.11

    - $VENV/bin/pip install --upgrade -r $APPDIR/requirements.txt
    - cd $APPDIR && $VENV/bin/python manage.py migrate --noinput
    - cd $APPDIR && $VENV/bin/python manage.py collectstatic --noinput
    - /bin/touch $APPDIR/passenger_wsgi.py
