line-length = 100
target-version = "py310"

[lint]
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # isort-compatible import sorting
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
  "SIM", # flake8-simplify
  "ISC", # implicit-str-concat
]
ignore = []

[format]
quote-style = "preserve"
skip-magic-trailing-comma = false
indent-style = "space"
line-ending = "lf"
